// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: vlove.proto

package vlove.protobuf;

@SuppressWarnings("all")
public final class VloveProtoMessage {
  private VloveProtoMessage() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface VloveOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required int32 id = 1;
    boolean hasId();
    int getId();
    
    // required .vlove.Vlove.Operation op = 2;
    boolean hasOp();
    vlove.protobuf.VloveProtoMessage.Vlove.Operation getOp();
  }
  public static final class Vlove extends
      com.google.protobuf.GeneratedMessage
      implements VloveOrBuilder {
    // Use Vlove.newBuilder() to construct.
    private Vlove(Builder builder) {
      super(builder);
    }
    private Vlove(boolean noInit) {}
    
    private static final Vlove defaultInstance;
    public static Vlove getDefaultInstance() {
      return defaultInstance;
    }
    
    public Vlove getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return vlove.protobuf.VloveProtoMessage.internal_static_vlove_Vlove_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return vlove.protobuf.VloveProtoMessage.internal_static_vlove_Vlove_fieldAccessorTable;
    }
    
    public enum Operation
        implements com.google.protobuf.ProtocolMessageEnum {
      LIST(0, 0),
      CREATE(1, 1),
      UPDATE(2, 2),
      DELETE(3, 3),
      ;
      
      public static final int LIST_VALUE = 0;
      public static final int CREATE_VALUE = 1;
      public static final int UPDATE_VALUE = 2;
      public static final int DELETE_VALUE = 3;
      
      
      public final int getNumber() { return value; }
      
      public static Operation valueOf(int value) {
        switch (value) {
          case 0: return LIST;
          case 1: return CREATE;
          case 2: return UPDATE;
          case 3: return DELETE;
          default: return null;
        }
      }
      
      public static com.google.protobuf.Internal.EnumLiteMap<Operation>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<Operation>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Operation>() {
              public Operation findValueByNumber(int number) {
                return Operation.valueOf(number);
              }
            };
      
      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return vlove.protobuf.VloveProtoMessage.Vlove.getDescriptor().getEnumTypes().get(0);
      }
      
      private static final Operation[] VALUES = {
        LIST, CREATE, UPDATE, DELETE, 
      };
      
      public static Operation valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }
      
      private final int index;
      private final int value;
      
      private Operation(int index, int value) {
        this.index = index;
        this.value = value;
      }
      
      // @@protoc_insertion_point(enum_scope:vlove.Vlove.Operation)
    }
    
    private int bitField0_;
    // required int32 id = 1;
    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public int getId() {
      return id_;
    }
    
    // required .vlove.Vlove.Operation op = 2;
    public static final int OP_FIELD_NUMBER = 2;
    private vlove.protobuf.VloveProtoMessage.Vlove.Operation op_;
    public boolean hasOp() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public vlove.protobuf.VloveProtoMessage.Vlove.Operation getOp() {
      return op_;
    }
    
    private void initFields() {
      id_ = 0;
      op_ = vlove.protobuf.VloveProtoMessage.Vlove.Operation.LIST;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasOp()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeEnum(2, op_.getNumber());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, op_.getNumber());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static vlove.protobuf.VloveProtoMessage.Vlove parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static vlove.protobuf.VloveProtoMessage.Vlove parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static vlove.protobuf.VloveProtoMessage.Vlove parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static vlove.protobuf.VloveProtoMessage.Vlove parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static vlove.protobuf.VloveProtoMessage.Vlove parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static vlove.protobuf.VloveProtoMessage.Vlove parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static vlove.protobuf.VloveProtoMessage.Vlove parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static vlove.protobuf.VloveProtoMessage.Vlove parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static vlove.protobuf.VloveProtoMessage.Vlove parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static vlove.protobuf.VloveProtoMessage.Vlove parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(vlove.protobuf.VloveProtoMessage.Vlove prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements vlove.protobuf.VloveProtoMessage.VloveOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return vlove.protobuf.VloveProtoMessage.internal_static_vlove_Vlove_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return vlove.protobuf.VloveProtoMessage.internal_static_vlove_Vlove_fieldAccessorTable;
      }
      
      // Construct using vlove.protobuf.VloveProtoMessage.Vlove.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        id_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        op_ = vlove.protobuf.VloveProtoMessage.Vlove.Operation.LIST;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return vlove.protobuf.VloveProtoMessage.Vlove.getDescriptor();
      }
      
      public vlove.protobuf.VloveProtoMessage.Vlove getDefaultInstanceForType() {
        return vlove.protobuf.VloveProtoMessage.Vlove.getDefaultInstance();
      }
      
      public vlove.protobuf.VloveProtoMessage.Vlove build() {
        vlove.protobuf.VloveProtoMessage.Vlove result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private vlove.protobuf.VloveProtoMessage.Vlove buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        vlove.protobuf.VloveProtoMessage.Vlove result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public vlove.protobuf.VloveProtoMessage.Vlove buildPartial() {
        vlove.protobuf.VloveProtoMessage.Vlove result = new vlove.protobuf.VloveProtoMessage.Vlove(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.op_ = op_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof vlove.protobuf.VloveProtoMessage.Vlove) {
          return mergeFrom((vlove.protobuf.VloveProtoMessage.Vlove)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(vlove.protobuf.VloveProtoMessage.Vlove other) {
        if (other == vlove.protobuf.VloveProtoMessage.Vlove.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasOp()) {
          setOp(other.getOp());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasId()) {
          
          return false;
        }
        if (!hasOp()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              id_ = input.readInt32();
              break;
            }
            case 16: {
              int rawValue = input.readEnum();
              vlove.protobuf.VloveProtoMessage.Vlove.Operation value = vlove.protobuf.VloveProtoMessage.Vlove.Operation.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(2, rawValue);
              } else {
                bitField0_ |= 0x00000002;
                op_ = value;
              }
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required int32 id = 1;
      private int id_ ;
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public int getId() {
        return id_;
      }
      public Builder setId(int value) {
        bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0;
        onChanged();
        return this;
      }
      
      // required .vlove.Vlove.Operation op = 2;
      private vlove.protobuf.VloveProtoMessage.Vlove.Operation op_ = vlove.protobuf.VloveProtoMessage.Vlove.Operation.LIST;
      public boolean hasOp() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public vlove.protobuf.VloveProtoMessage.Vlove.Operation getOp() {
        return op_;
      }
      public Builder setOp(vlove.protobuf.VloveProtoMessage.Vlove.Operation value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000002;
        op_ = value;
        onChanged();
        return this;
      }
      public Builder clearOp() {
        bitField0_ = (bitField0_ & ~0x00000002);
        op_ = vlove.protobuf.VloveProtoMessage.Vlove.Operation.LIST;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:vlove.Vlove)
    }
    
    static {
      defaultInstance = new Vlove(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:vlove.Vlove)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_vlove_Vlove_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_vlove_Vlove_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013vlove.proto\022\005vlove\"r\n\005Vlove\022\n\n\002id\030\001 \002(" +
      "\005\022\"\n\002op\030\002 \002(\0162\026.vlove.Vlove.Operation\"9\n" +
      "\tOperation\022\010\n\004LIST\020\000\022\n\n\006CREATE\020\001\022\n\n\006UPDA" +
      "TE\020\002\022\n\n\006DELETE\020\003B#\n\016vlove.protobufB\021Vlov" +
      "eProtoMessage"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_vlove_Vlove_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_vlove_Vlove_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_vlove_Vlove_descriptor,
              new java.lang.String[] { "Id", "Op", },
              vlove.protobuf.VloveProtoMessage.Vlove.class,
              vlove.protobuf.VloveProtoMessage.Vlove.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
